apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-kube-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: boot-kube
      tier: app
  template:
    metadata:
      labels:
        app: boot-kube
        tier: app
    spec:
      containers:
        - name: boot-kube
          image: bmsvega2k/boot-kube:0.1